### ISSUE TITLE
Possible to use it in JS2-mode?

### ISSUE THREAD

**Issue by ianyepan** [magnars/tagedit#18]
I really love the experimental auto-close tag feature in HTML-mode. Is there any way I could extend it to writing JavaScript code? I added the following in my `.emacs`:
```lisp
(eval-after-load 'sgml-mode
  '(progn
     (require 'tagedit)
     (tagedit-add-paredit-like-keybindings)
     (add-hook 'html-mode-hook (lambda () (tagedit-mode 1)))
     (add-hook 'js2-mode-hook (lambda () (tagedit-mode 1)))))

(add-hook 'js2-mode-hook tagedit-mode)
(tagedit-add-experimental-features)
```
But it didn't seem to work...

**Comment by magnars** [comment]
No, sorry. tagedit leans on sgml-mode, which does not work in js2-mode buffers. I see someone is working on a jsx-mode. Maybe parts of tagedit could be extracted and made to work there somehow?

**Comment by ianyepan** [comment]
I see, I'll keep myself updated. Thanks for the reply.
